### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Riv67** [Riv67/events-calendar#1]
For the boxes of the calendar, do I have to add div tags inside each td? So for the events, each event would be in a separate div?

Do I put any code in the empty box that spans 5 columns?

Also, is “November, 1963" considered a title or a caption?

Thanks :) @muxlowc @mackenzierose

**Comment by MacKenzieRose** [comment]
Yes, definitely add div tags for each td. You can treat the events as additional divs, or also as lists inside of the div tags (inside of each td).

The empty box should have the non-breaking space code (& n b s p <-- with no spaces)

November 1963 will get the caption tag

**Comment by Riv67** [comment]
Thanks!
