### ISSUE TITLE
Not sure what I did wrong...

### ISSUE THREAD

**Issue by Riv67** [Riv67/events-calendar#2]
For some reason my classes are not styling anything, not sure why. I’ve copied and pasted all the typographer settings and linked the css page correctly. Do you see why this might be happening?
@muxlowc @mackenzierose

**Comment by MacKenzieRose** [comment]
If the code you've got on Github is up-to-date, I see a few things.

Grid.css is empty, and type.css has the modulifier content in it. I also don't see a css link for your grid in your index file.

Let me know if those changes fix it!

**Comment by muxlowc** [comment]
@Riv67  what MacKenzie said!

Also, it seems to be okay when I forked it - you just need to add in some borders to your TD and THs and height to your tbody tds :)

**Comment by Riv67** [comment]
Okay thanks! That’s already helped a lot. Do I need to include the grid.css?

**Comment by muxlowc** [comment]
@Riv67  nope, you can remove it for this assignment!

**Comment by Riv67** [comment]
Okay great :)
