### ISSUE TITLE
Sizing the boxes

### ISSUE THREAD

**Issue by Riv67** [Riv67/events-calendar#3]
I’ve been trying all sorts of things to fix the height and width of the boxes/cells but with no luck. I’m not sure what to target or what numbers will make it fit. As you can see, right now I’ve targeted the “day” class in my css and put a height on it, but it isn’t really working. Help please!
@muxlowc @mackenzierose

**Comment by muxlowc** [comment]
@Riv67  try removing your .day {height: 6rem} from your css and add this instead:

tbody td {
  height: 11em;
}

**Comment by MacKenzieRose** [comment]
Unrelated to the above, but also make sure to escape the non-breaking space (by writing with a semicolon --> &nbsp; ) or you'll get some really weird errors in rendering your page :)

**Comment by MacKenzieRose** [comment]
**& n b s p ; <--with no spaces

**Comment by Riv67** [comment]
Ooo much better! The top row is still a bit tall but Markbot will take it :) Thanks!

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
